# Numpy

In [1]:
# creating array in Numpy
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5]) # convert python list into np array
print("1D Array: ", arr_1d)

1D Array:  [1 2 3 4 5]


In [3]:
# List vs np array
py_list = [1,2,3,4,5]
print("Python list multiplication", py_list * 2)

np_arr = np.array([1,2,3,4,5])
print("Numpy array multiplication", np_arr * 2)

Python list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication [ 2  4  6  8 10]


In [6]:
# Calculation difference
import time

start_time = time.time()
py_list = [ i * 2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start_time)

start = time.time()
np_arr = np.arange(10000000) * 2
print("\n Numpy array operation time: ", time.time() - start)


 List operation time:  1.1853673458099365

 Numpy array operation time:  0.03340291976928711


In [7]:
# create 2d array
arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D Array: ", arr_2d)

2D Array:  [[1 2 3]
 [4 5 6]]


In [8]:
# create array from scratch

zeros = np.zeros((3,4))
print("Zeros: ", zeros)

ones = np.ones((3,4))
print("Ones: ", ones)

empty = np.empty((3,4))
print("Empty: ", empty)

Zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# 1D array creation
np.arange(10)
print("Arange: ", np.arange(10))

Arange:  [0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.arange(2, 3, 0.2))

[2.  2.2 2.4 2.6 2.8]


In [18]:
print(np.linspace(1., 4., 10))

[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.        ]


In [17]:
# random number generation
random = np.random.rand(3,4)
print("Random: ", random)

Random:  [[0.79156694 0.21850488 0.14378049 0.95890959]
 [0.03633722 0.17111993 0.77171798 0.37487194]
 [0.17809507 0.25339733 0.67633973 0.49140935]]


In [19]:
print(random.shape) # used for knowing the shape of the array

(3, 4)


In [20]:
print(arr_1d.shape)

(5,)


In [23]:
# properties of array

arr = np.array([[1,2,3], [4,5,6]])

print("shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)
print("Item size: ", arr.itemsize)
print("Data: ", arr.data)

shape: (2, 3)
Dimension: 2
Size:  6
Data type:  <U21
Item size:  84
Data:  <memory at 0x79aa471d68e0>


In [26]:
# Indexing and slicing

arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) # 3rd element
print(arr[2:4]) # 3rd and 4th element
print(arr[0:5:3])

30
[30 40]
[10 40]


In [27]:
# shortcut
print(arr[:3]) # fromt start to inde 2

[10 20 30]


In [29]:
print(arr[3:])
print(arr[:])
# negative indexing same as python list

[40 50]
[10 20 30 40 50]


In [30]:
# 2D array indexing

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix[1,2])

6


In [32]:
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [33]:
print(matrix[1])

[4 5 6]


In [34]:
print(matrix[:,1])

[2 5 8]


In [39]:
# Filtering
arr = np.array([10,20,30,40,50,60])
print(arr>25)

[False False  True  True  True  True]


In [37]:
arr = np.array ([1,2,3,4,5,6,7,8,9])
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[2 4 6 8]


In [40]:
print(arr[arr>25])

[30 40 50 60]


In [41]:
print(arr[(arr>25) & (arr<50)])

[30 40]


In [50]:
# mask
arr = np.array([10,20,30,40,50,60])
arr[arr > 25] = 0
print(arr)

[10 20  0  0  0  0]


In [44]:
print(arr[[1,2,4]])

[20 30 50]


In [45]:
# slicing changes the original array

a = np.array([1,2,3,4])
b = a[1:3]

print(a)
print(b)

b[0] = 9999

print(a)

[1 2 3 4]
[2 3]
[   1 9999    3    4]


In [47]:
a = np.array([1,2,3,4])
b = a[1:3].copy()

print(a)
print(b)

b[0] = 9999

print(a)
print(b)

[1 2 3 4]
[2 3]
[1 2 3 4]
[9999    3]


In [52]:
arr = np.array([1, 2, 3])

print(arr + 2)
print(arr * 3)

[3 4 5]
[3 6 9]


In [53]:
# adding and removing the data
print(np.append(arr, 5))
print(np.delete(arr, 1))

[1 2 3 5]
[1 3]


In [57]:
# array concatenation
a = np.array([1,2,3])
b = np.array([4,5,6])

combined = a + b

print(combined)

[5 7 9]


In [55]:
combined = np.concatenate((a,b))
print(combined)

[1 2 3 4 5 6]


In [58]:
print(np.sum(a))
print(np.mean(a))

6
2.0


In [59]:
# mathematical function
print(np.sqrt(a))
print(np.log(a))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [60]:
# dot product  (@)
print(np.dot(a,b))

32


In [64]:
# Reshape & Flatten

arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [70]:
c = arr.reshape(2,4)
print(c)
print(c.ndim)

[[0 1 2 3]
 [4 5 6 7]]
2


In [73]:
print(c.flatten())
print(c.ndim)

[0 1 2 3 4 5 6 7]
2


In [74]:
print(c.ravel())
print(c.ndim)

[0 1 2 3 4 5 6 7]
2
